name: Veracode Static Analysis Demo
on: [push]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # zip the project and move it to a staging directory
      - name: Zip Project
        run: zip -R project.zip '*.py' '*.js' '*.php' '*.ts' '*.css' '*.hbs'
        env:
          build-name: project.zip

      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: CodePackage
          path: project.zip

  static_analysis:
    needs: build
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v2

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          appname: "Demo"
          createprofile: false
          filepath: "project.zip"
          vid: "fb89935f9488375f52cdf8e8981621c1"
          vkey: "9d57b45f85775eecaa3f69502553fb22c718911e3ea645642da7c620d0fc51855b47a933444b513db0be39f0a994f679ea6bd2fe8462088538d34942c2559d5e"
#          createsandbox: 'true'
#          sandboxname: 'SANDBOXNAME'
#          scantimeout: 0
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'
